### ISSUE TITLE
QGIS 3.2.0 crashes when exporting image including Google satellite with openlayers-plugin

### ISSUE THREAD

**Issue by pgiraudoux** [sourcepole/qgis-openlayers-plugin#58]
There are anomalies when using the Openlayer plugin,  Google map > Google satellite. Exporting any kind of image (File > Export > Export Map to Image) leads to a complete crash.
Here below the crash report.
Best,

Crash ID: 059fc511cf0597c0396959d1053938bd93019461

Stack Trace

WTFCrash :
JSC::evaluate :
JSPropertyNameArrayGetCount :
JSPropertyNameArrayGetCount :
WKConnectionGetTypeID :
QWebFrameAdapter::evaluateJavaScript :
QWebFrame::evaluateJavaScript :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaMethod::invoke :
QMetaObject::invokeMethod :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_sip :
std::basic_string,std::allocator >::shrink_to_fit :
QgsPresetSchemeColorRamp::clone :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsMapRendererTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.2.0-Bonn
QGIS code revision: bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by dtvkoe** [comment]
I have the same problem when using Google Phyiscal map or Google Road map.

My crash report:

```
Crash ID: 059fc511cf0597c0396959d1053938bd93019461


Stack Trace


WTFCrash :
JSC::evaluate :
JSPropertyNameArrayGetCount :
JSPropertyNameArrayGetCount :
WKConnectionGetTypeID :
QWebFrameAdapter::evaluateJavaScript :
QWebFrame::evaluateJavaScript :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaMethod::invoke :
QMetaObject::invokeMethod :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_sip :
std::basic_string,std::allocator >::shrink_to_fit :
QgsPresetSchemeColorRamp::clone :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsMapRendererTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.2.1-Bonn
QGIS code revision: 1edf372fb8
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4



System 
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134
```

**Comment by dtvkoe** [comment]
QGIS also crashes on Linux OS (Linux Mint 19 64bit) when using the export with active javascript API based layer. 
Unfortunatelety the crash happens without showing a crash report box afterwards.

tested with the hereinafter QGIS version:
````
QGIS version 3.2.1-Bonn
QGIS code revision 1edf372
Compiled against Qt 5.9.5
Running against Qt 5.9.5
Compiled against GDAL/OGR 2.2.3
Running against GDAL/OGR 2.2.3
Compiled against GEOS 3.6.2-CAPI-1.10.2
Running against GEOS 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version 10.3 (Ubuntu 10.3-1)
SpatiaLite Version 4.3.0a
QWT Version 6.1.3
QScintilla2 Version 2.10.2
PROJ.4 Version 493
```

**Comment by pka** [comment]
Thanks for the report. I was able to reproduce a silent crash on Ubuntu as well. Seems like QGIS messed up with PluginLayers again. We fixed PluginLayer support in 3.0.1 and will have another look at it.

**Comment by ThirstyGeo** [comment]
I can confirm that this issue is still present in QGIS 3.4.0 on Windows 10

**Comment by HusseinKabbout** [comment]
This problem doesn't occur in the new QGIS LTR(3.10.3). I tested it on Linux(Fedora 30) and on windows 10.

**Comment by tcurdt** [comment]
QGIS version 3.20.2-Odense (9f59a15664) crashes for most maps on macOS 10.15.7. So far I've only found openstreetmap to be working.
